#specify the language
language: python

#specify the version
python:
  - "3.5"

install:
  - pip install python-coveralls

#specify the task
script: coverage run -m unittest



after_success:
  - coveralls

